version: '3'
services:
  gateway:
    build: ssh-gateway
    network_mode: host
    depends_on:
      - "emq"
  forward:
    build: ssh-forward
    network_mode: host
  emq:
    build: git://github.com/emqtt/emq-docker
    network_mode: host
    environment:
     - EMQ_NAME=emq
     - EMQ_HOST=127.0.0.1
